# This is a config for E2B sandbox template.
# You can use template ID (30cjeoeatr1ek38ntnsw) or template name (vibe-next-js-baserohit) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-js-baserohit") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-js-baserohit") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-js-baserohit')

team_id = "9408c2fa-cd88-4501-b885-ff4f210f920c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-js-baserohit"
template_id = "30cjeoeatr1ek38ntnsw"
